<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>home</name>
   <tag></tag>
   <elementGuidId>0cc467e8-d5b4-4970-b0cf-ff7f275b957c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='로그아웃'])[1]/following::span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.side-menu-item.active > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>477efee4-17f6-46a0-9972-4848b33e35ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>홈</value>
      <webElementGuid>7daf8659-13f7-4226-8c74-d08be8a21fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-layout-container[1]/app-side-menu[1]/div[@class=&quot;nav-wrap&quot;]/nav[1]/app-side-menu-list[1]/div[1]/ul[@class=&quot;list-unstyled main-menu&quot;]/div[1]/app-side-menu-item[1]/li[1]/a[@class=&quot;side-menu-item active&quot;]/span[1]</value>
      <webElementGuid>fee0675e-7654-4b51-bcd6-cca0a9b84dea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='로그아웃'])[1]/following::span[2]</value>
      <webElementGuid>8bf110e3-4069-4be7-9b13-7c960b7abdd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='문자 발송 신청서'])[1]/following::span[2]</value>
      <webElementGuid>cd4bc5ec-267d-465b-8df9-aa072bf1d77a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='병원 정보'])[1]/preceding::span[1]</value>
      <webElementGuid>1dc23063-b1a5-4774-97ca-ebbcac827d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='병원 정보'])[2]/preceding::span[3]</value>
      <webElementGuid>18e5bbf7-e3ab-4122-be13-be3aaf2d58b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='홈']/parent::*</value>
      <webElementGuid>167efda7-1529-41c4-8471-fd025112c85e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>8119445e-4557-4384-883a-6f1473547bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '홈' or . = '홈')]</value>
      <webElementGuid>0a53b530-ffff-4c58-839b-a375ce41755d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
