<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_저장</name>
   <tag></tag>
   <elementGuidId>ee226df6-8576-4ac5-b0f7-722e09c491d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[(text() = ' 저장 ' or . = ' 저장 ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.ha-btn.ha-btn-spec</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[(text() = ' 저장 ' or . = ' 저장 ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4202601e-37cf-4088-9c41-c940eae64854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autoclose</name>
      <type>Main</type>
      <value>inside</value>
      <webElementGuid>f4ae4df3-5aca-4242-90fe-48e7d15f8ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>c76c5823-2737-40bd-b8dd-e5d096b8f807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>triggers</name>
      <type>Main</type>
      <value>manual</value>
      <webElementGuid>7fb0c8d5-70e7-4c0c-b93d-ae2784a152c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn ha-btn ha-btn-spec</value>
      <webElementGuid>0f2ab6f1-225e-42fe-954e-998ec18ebe71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 저장 </value>
      <webElementGuid>910e3a8f-a7c5-4277-8194-ccdcb6e2cea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-layout-container[1]/div[@class=&quot;main container-fluid scroll-x&quot;]/app-hospital-info-container[1]/div[1]/div[@class=&quot;container&quot;]/app-hospital-info-set[1]/app-container-footer[@class=&quot;footer-section&quot;]/div[@class=&quot;container-footer d-flex&quot;]/div[@class=&quot;btn-wrap flex-shrink-1 text-right&quot;]/button[@class=&quot;btn ha-btn ha-btn-spec&quot;]</value>
      <webElementGuid>6eeb73bf-9d88-43da-9985-5edd2a3383b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ 추가'])[2]/following::button[1]</value>
      <webElementGuid>636791de-193d-4938-91b0-2a53367392ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='장비명/장비 대수'])[1]/following::button[2]</value>
      <webElementGuid>95ab4784-5aa3-4c7a-93ef-4ffe2c45b262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='알림'])[1]/preceding::button[1]</value>
      <webElementGuid>70c5b566-2ed0-4a9b-b52a-7d81be715b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='확인'])[1]/preceding::button[1]</value>
      <webElementGuid>c2b7e769-4bbd-4919-a9c0-457e20b28048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='저장']/parent::*</value>
      <webElementGuid>5d9cd05a-8e47-41a1-b990-8bb84fb9dad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-container-footer/div/div[2]/button</value>
      <webElementGuid>b621069e-45ca-4356-8f41-cbddef986fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' 저장 ' or . = ' 저장 ')]</value>
      <webElementGuid>79dcc4b7-c17c-4e39-bb60-0990f84632ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
