<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_save</name>
   <tag></tag>
   <elementGuidId>93ec1a24-849a-40d1-a2c5-460cdb13da70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.ha-btn.ha-btn-spec</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[(text() = ' 저장 ' or . = ' 저장 ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4dd0bd8a-19e6-49a6-b2f3-a1a21036659d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autoclose</name>
      <type>Main</type>
      <value>inside</value>
      <webElementGuid>f2e836d2-e343-4245-a42b-fef73400acba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>54769604-ae82-46c5-bfaf-47325a89905a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>triggers</name>
      <type>Main</type>
      <value>manual</value>
      <webElementGuid>f9118a58-c602-4f99-aeef-1f6cdcbeef16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn ha-btn ha-btn-spec</value>
      <webElementGuid>2ad8a483-8544-4347-807a-a7512f12557f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 저장 </value>
      <webElementGuid>d0a7e7da-d7a5-4c0f-9230-bd82330bf2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-layout-container[1]/div[@class=&quot;main container-fluid scroll-x&quot;]/app-hospital-notice-set-page[1]/app-container-footer[1]/div[@class=&quot;container-footer d-flex&quot;]/div[@class=&quot;btn-wrap flex-shrink-1 text-right&quot;]/button[@class=&quot;btn ha-btn ha-btn-spec&quot;]</value>
      <webElementGuid>9c5bd1c7-65ab-45db-9204-6712905a1a19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='취소'])[1]/following::button[1]</value>
      <webElementGuid>d494c0ce-b3cd-49cb-9785-f11e0341c85f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0/200)'])[1]/following::button[2]</value>
      <webElementGuid>d0ce10d3-65e0-463b-99f1-88821f2fd706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='알림'])[1]/preceding::button[1]</value>
      <webElementGuid>01ab9ec2-8142-4846-822c-12bc47038ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='확인'])[1]/preceding::button[1]</value>
      <webElementGuid>54cd50e9-99b5-4734-a368-fac65a216650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='저장']/parent::*</value>
      <webElementGuid>0bd97801-2a8a-47f6-a3e4-dc839aa74f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>24e0cf98-bf41-431a-b804-86fa8adf700c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' 저장 ' or . = ' 저장 ')]</value>
      <webElementGuid>dd0eeef0-cb89-447f-a125-fb47ff31249d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
