<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>notice_btn_saveConfirm22</name>
   <tag></tag>
   <elementGuidId>35a8998f-a9db-4a35-85bb-f5bf8228a870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id = 'btnAccept' and @type = 'button' and (text() = ' 확인 ' or . = ' 확인 ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnAccept</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9729bd17-7bcb-4909-aa86-16c69b0a9152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAccept</value>
      <webElementGuid>9f3863bb-40f4-46d5-985b-ad35387d2388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c4cb072b-6b7b-4718-8cd6-a7cf952408c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ha-btn ha-btn-primary</value>
      <webElementGuid>82c316d9-9ed7-47ee-a368-9a0659ad4435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 확인 </value>
      <webElementGuid>b844b8ed-d786-4751-8a57-49502d73c965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAccept&quot;)</value>
      <webElementGuid>1dfc8da8-8b90-4772-b9a5-24576d2700b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnAccept']</value>
      <webElementGuid>8f323cab-8a71-49ff-8beb-e57a26e8ab36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='내용을 입력해주세요'])[1]/following::button[1]</value>
      <webElementGuid>b428dddc-1fd8-4bc5-959d-6e1cbb6ed1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='알림'])[1]/following::button[1]</value>
      <webElementGuid>eb3063e8-6ed8-4dbc-b39b-173d1832ce7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='확인'])[2]/preceding::button[2]</value>
      <webElementGuid>2a23fdc9-b953-43c8-bafd-b5eed736bbcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[3]</value>
      <webElementGuid>f47461b3-63ae-4e42-9487-15899b1cb901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='확인']/parent::*</value>
      <webElementGuid>645ca297-96e9-4468-aa2f-e26b226f1ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button</value>
      <webElementGuid>a7231f91-0043-4cd4-b155-a7e85933a9ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnAccept' and @type = 'button' and (text() = ' 확인 ' or . = ' 확인 ')]</value>
      <webElementGuid>496d1e10-48a1-4764-aff7-67dd27aa0583</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
