<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>notice_input_description</name>
   <tag></tag>
   <elementGuidId>f992ef81-59bd-4b78-baeb-10160e0fcc5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtReserveMemo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtReserveMemo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>918f8ed2-ca64-4b6d-aa3c-0cc90a4ed630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>0cb3c2db-4b08-4807-9893-aa5c298cc2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>df3ffaab-2800-4b21-b2de-c000d441b2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtReserveMemo</value>
      <webElementGuid>2acc1170-9125-4c69-a04c-b4db76b6b0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ex)
접수 후 도착하시면 데스크에 알려주세요.
진료차례가 되어도 내원하지 않으면 자동 취소됩니다.</value>
      <webElementGuid>1b933827-7cec-4c8e-ada6-c0775ba37a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>3aab0781-290d-41ce-895e-5546006dd3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>d1a89207-76aa-4121-a8ed-3e091ea21215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtReserveMemo&quot;)</value>
      <webElementGuid>6b72375f-83e0-41a0-8958-3360c0a9aea9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtReserveMemo']</value>
      <webElementGuid>5926f3d1-ba65-4fca-b720-7301c42c9366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0/20)'])[1]/following::textarea[1]</value>
      <webElementGuid>f726ad49-b5b4-4512-8a7c-0625ec899ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='공지사항 설정'])[1]/following::textarea[1]</value>
      <webElementGuid>d9c027f3-5456-455f-9df1-d1acaca01dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0/200)'])[1]/preceding::textarea[1]</value>
      <webElementGuid>a371ea80-c3eb-4fd4-bbd3-982740c9e928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='취소'])[1]/preceding::textarea[1]</value>
      <webElementGuid>acdc525a-6671-4a58-b506-812e712e6f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>66f925c9-fc6b-4d1f-8978-158a36b44bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'txtReserveMemo' and @placeholder = 'ex)
접수 후 도착하시면 데스크에 알려주세요.
진료차례가 되어도 내원하지 않으면 자동 취소됩니다.']</value>
      <webElementGuid>eff9cf5a-e54a-410e-aa0d-99f83ca265e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
