<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__월요일 시작 시</name>
   <tag></tag>
   <elementGuidId>26ff34d3-a6f3-4842-b528-9a186a4a2c04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ngb-tp-input.form-control</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aed963df-bfbd-452b-8e31-2e30a9f4fce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b8c0af3-3a24-4a62-9b75-d794dfb79b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7f73ef51-fe2a-4b71-9e3d-e13963a3d38f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>e7a17b22-d19d-4da6-bde2-150362c6b49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>HH</value>
      <webElementGuid>7e370703-a07a-4377-b284-4b69a67f6c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Hours</value>
      <webElementGuid>fc012be7-0487-4466-a774-d614d215942f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ngb-tp-input form-control</value>
      <webElementGuid>ff412505-04ed-4d9b-8f5e-6367a53e6cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-layout-container[1]/div[@class=&quot;main container-fluid scroll-x&quot;]/app-operating-time-set-page[1]/div[@class=&quot;container&quot;]/app-operating-time-set[1]/div[@class=&quot;ha-card ha-card-radius&quot;]/div[2]/div[1]/app-operating-time-set-item[1]/div[@class=&quot;ha-row ha-row-border time-setter ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;ha-col time-column&quot;]/div[@class=&quot;timepicker-wrap&quot;]/ngb-timepicker[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/fieldset[1]/div[@class=&quot;ngb-tp&quot;]/div[@class=&quot;ngb-tp-input-container ngb-tp-hour&quot;]/input[@class=&quot;ngb-tp-input form-control&quot;]</value>
      <webElementGuid>71928368-ecf3-4540-bf84-6aee62d0e35d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>4deaae53-0c9a-4636-bdd8-fde0250289ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a0598ca7-6487-40ff-858c-02ec2e91ba4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'HH']</value>
      <webElementGuid>14f14583-9c0d-47e8-9432-1009157e36c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
