<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__HH 확인</name>
   <tag></tag>
   <elementGuidId>8ca23d8f-bb06-47c3-ad94-5e6bb8b4a13c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ngb-tp-input.form-control</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77850f0f-254a-46b4-9987-0340390e0908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2ca41d9-7d87-4536-bf54-9926174718c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>00354ee2-9664-4fba-bf28-6c884fb8e37a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>7ab8bbf7-22d8-43c6-be30-c6154b4cb1fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>HH</value>
      <webElementGuid>40f01703-9c29-4ebf-818f-aafc819b5e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Hours</value>
      <webElementGuid>4856df76-5eff-403a-bd5e-3046dc8c26fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ngb-tp-input form-control</value>
      <webElementGuid>f92a5b1a-65cd-4b8c-9667-1c88cb312924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-layout-container[1]/div[@class=&quot;main container-fluid scroll-x&quot;]/app-operating-time-set-page[1]/div[@class=&quot;container&quot;]/app-operating-time-set[1]/div[@class=&quot;ha-card ha-card-radius&quot;]/div[2]/div[1]/app-operating-time-set-item[1]/div[@class=&quot;ha-row ha-row-border time-setter ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;ha-col time-column&quot;]/div[@class=&quot;timepicker-wrap&quot;]/ngb-timepicker[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/fieldset[1]/div[@class=&quot;ngb-tp&quot;]/div[@class=&quot;ngb-tp-input-container ngb-tp-hour&quot;]/input[@class=&quot;ngb-tp-input form-control&quot;]</value>
      <webElementGuid>8eb4f98e-f9b9-4f10-95ef-dd723fc7f80c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>80844845-0295-4ded-bb5a-3a29643d777f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>57aac747-e5b8-4396-bb37-09793c8a5586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'HH']</value>
      <webElementGuid>5d97c83a-9f3f-4441-b4ac-23814e4e34a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
