<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pre_업데이트 되었습니다</name>
   <tag></tag>
   <elementGuidId>f212014c-3ed8-4624-beb9-1f5ba005b3b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='알림'])[1]/following::pre[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>pre.ham-body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>pre</value>
      <webElementGuid>9d89e73c-a8b6-4118-8426-b519fdbf3634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ham-body</value>
      <webElementGuid>160e1631-b66b-4bbc-826c-faf30ba96ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>업데이트되었습니다.</value>
      <webElementGuid>0b6cd0b8-a8f3-4db1-8be7-5fd2a8815ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-alert-modal[1]/div[@class=&quot;ham-overlay ham-show&quot;]/div[@class=&quot;ham-inner-t&quot;]/div[@class=&quot;ham-inner-c&quot;]/div[@class=&quot;ham-section&quot;]/pre[@class=&quot;ham-body&quot;]</value>
      <webElementGuid>548183d0-4dea-4d75-94de-ba327425151d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='알림'])[1]/following::pre[1]</value>
      <webElementGuid>1a3b1eed-0102-452a-9ad4-ca97a3333426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='설정 안 함'])[2]/following::pre[1]</value>
      <webElementGuid>09def77c-6996-4579-9ede-544352461d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='확인'])[1]/preceding::pre[1]</value>
      <webElementGuid>11eda8b5-f466-4181-a37c-b3836dbf6427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='확인'])[2]/preceding::pre[2]</value>
      <webElementGuid>cb0c31eb-ff79-4c7b-98aa-2fc209cf8e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='업데이트되었습니다.']/parent::*</value>
      <webElementGuid>c370bd07-b211-4989-b33c-d615419599fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/pre</value>
      <webElementGuid>52ef03dc-870e-42d2-8859-9993e3ed24a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//pre[(text() = '업데이트되었습니다.' or . = '업데이트되었습니다.')]</value>
      <webElementGuid>6ff2f1b4-8f5a-4cf9-bdfc-206fa830516a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
